add quotes, drop semicolon

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,32 +35,38 @@ jobs:
       - name: Apt install system dependencies (linux)
         if: ${{ startsWith(matrix.os, 'ubuntu-') }}
         run: |
-          echo ::group::Run sudo apt-get update; sudo apt-get update; echo ::endgroup::
-          echo ::group::Run sudo apt-get install texlive texlive-fonts-extra texlive-humanities latexmk;
+          echo "::group::Run sudo apt-get update"
+          sudo apt-get update
+          echo "::endgroup::"
+          echo "::group::Run sudo apt-get install texlive texlive-fonts-extra texlive-humanities latexmk";
           sudo apt-get install texlive texlive-fonts-extra texlive-humanities latexmk;
-          echo ::endgroup::
+          echo "::endgroup::"
       - name: Setup Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
       - name: Pip install dependencies
         run: |
-          echo ::group::Run python -m pip install --upgrade pip setuptools wheel
+          echo "::group::Run python -m pip install --upgrade pip setuptools wheel"
           python -m pip install --upgrade pip setuptools wheel
-          echo ::endgroup::
-          echo ::group::Run pip install .[test] coverage
+          echo "::endgroup::"
+          echo "::group::Run pip install .[test] coverage"
           pip install .[test] coverage
-          echo ::endgroup::
+          echo "::endgroup::"
       - name: Run tests
         run: python run-tests.py
       - name: Run try-examples.py (linux)
         if: ${{ startsWith(matrix.os, 'ubuntu-') }}
         run: |
-          echo ::group::Run try-examples.py; FAILED=0;
+          echo "::group::Run try-examples.py"
+          FAILED=0;
           coverage run --append try-examples.py || FAILED=$?
-          echo ::endgroup::
-          echo ::group::Check coverage; coverage report; coverage html; echo ::endgroup::
-          [ $FAILED -eq 0 ] || echo ::warning::try-examples.py failed with exit code $FAILED
+          echo "::endgroup::"
+          echo "::group::Check coverage"
+          coverage report
+          coverage html
+          echo "::endgroup::"
+          [ $FAILED -eq 0 ] || echo "::warning::try-examples.py failed with exit code $FAILED"
         shell: bash
       - name: Upload coverage
         uses: codecov/codecov-action@v1
